language: php

addons:
  apt_packages:
    - locales
    - language-pack-en
    - language-pack-ro
    - language-pack-ro-base

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - sudo apt-get update
  - sudo locale-gen --no-purge --lang ro_RO.UTF-8
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.xml